# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_organ', models.BooleanField(default=False)),
                ('donor_blood', models.BooleanField(default=False)),
                ('donor_kidney', models.BooleanField(default=False)),
                ('donor_heart', models.BooleanField(default=False)),
                ('donor_lung', models.BooleanField(default=False)),
                ('donor_eye', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emer_blood', models.CharField(max_length=5)),
                ('emer_area', models.CharField(max_length=100)),
                ('emer_city', models.CharField(max_length=100)),
                ('emer_pin', models.IntegerField()),
                ('emer_start', models.DateTimeField(auto_now_add=True)),
                ('emer_status', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='needer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needer_organ', models.BooleanField(default=False)),
                ('needer_blood', models.BooleanField(default=False)),
                ('needer_kidney', models.BooleanField(default=False)),
                ('needer_heart', models.BooleanField(default=False)),
                ('needer_lung', models.BooleanField(default=False)),
                ('needer_eye', models.BooleanField(default=False)),
                ('needer_area', models.CharField(max_length=100)),
                ('needer_city', models.CharField(max_length=100)),
                ('needer_pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.IntegerField()),
                ('user_adhaar', models.BigIntegerField()),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_blood', models.CharField(max_length=5)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_area', models.CharField(max_length=100)),
                ('user_city', models.CharField(max_length=100)),
                ('user_pin', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='needer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.user'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.user'),
        ),
        migrations.AddField(
            model_name='donor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.user'),
        ),
    ]
